'use client';

/**
 * Export an HTML element as a PDF with NoteNova branding.
 * Uses html2pdf.js (client-side only).
 *
 * @param {HTMLElement} element - The DOM element to export
 * @param {string} filename - Download filename (without .pdf extension)
 */
export async function exportToPdf(element, filename = 'NoteNova-Export') {
  if (typeof window === 'undefined') return;

  const html2pdf = (await import('html2pdf.js')).default;

  // Create a wrapper that forces light theme for print
  const wrapper = document.createElement('div');
  wrapper.style.cssText = `
    background: #ffffff;
    color: #1a1a2e;
    padding: 40px 48px;
    font-family: 'Inter', system-ui, sans-serif;
    font-size: 14px;
    line-height: 1.7;
    max-width: 800px;
  `;

  // Header with branding
  const header = document.createElement('div');
  header.style.cssText = `
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 32px;
    padding-bottom: 16px;
    border-bottom: 2px solid #8B5CF6;
  `;
  header.innerHTML = `
    <div style="display: flex; align-items: center; gap: 8px;">
      <div style="width: 28px; height: 28px; border-radius: 6px; background: linear-gradient(135deg, #8B5CF6, #06B6D4); display: flex; align-items: center; justify-content: center;">
        <span style="color: white; font-size: 14px;">✦</span>
      </div>
      <span style="font-size: 16px; font-weight: 800; color: #1a1a2e;">
        Note<span style="background: linear-gradient(135deg, #8B5CF6, #06B6D4); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">Nova</span> AI
      </span>
    </div>
    <span style="font-size: 11px; color: #94A3B8;">${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
  `;

  // Clone content and fix styles for PDF
  const content = element.cloneNode(true);
  content.style.cssText = `
    color: #1a1a2e;
  `;

  // Fix all child element colors for light theme
  content.querySelectorAll('*').forEach(el => {
    const computed = window.getComputedStyle(el);
    if (computed.color === 'rgb(241, 245, 249)' || computed.color === 'rgb(148, 163, 184)') {
      el.style.color = '#1a1a2e';
    }
  });

  // Style headings
  content.querySelectorAll('h1, h2, h3').forEach(el => {
    el.style.color = '#1a1a2e';
    el.style.marginTop = '20px';
    el.style.marginBottom = '10px';
  });

  // Style code blocks
  content.querySelectorAll('pre').forEach(el => {
    el.style.background = '#f1f5f9';
    el.style.border = '1px solid #e2e8f0';
    el.style.borderRadius = '8px';
    el.style.padding = '12px';
    el.style.fontSize = '13px';
    el.style.overflow = 'hidden';
  });

  content.querySelectorAll('code').forEach(el => {
    if (!el.parentElement?.tagName?.toLowerCase()?.includes('pre')) {
      el.style.background = '#ede9fe';
      el.style.color = '#7C3AED';
      el.style.padding = '1px 4px';
      el.style.borderRadius = '3px';
    }
  });

  // Style tables
  content.querySelectorAll('table').forEach(el => {
    el.style.width = '100%';
    el.style.borderCollapse = 'collapse';
  });
  content.querySelectorAll('th, td').forEach(el => {
    el.style.border = '1px solid #e2e8f0';
    el.style.padding = '8px 12px';
    el.style.color = '#1a1a2e';
  });
  content.querySelectorAll('th').forEach(el => {
    el.style.background = '#f8fafc';
    el.style.fontWeight = '600';
  });

  // Style blockquotes
  content.querySelectorAll('blockquote').forEach(el => {
    el.style.borderLeft = '3px solid #8B5CF6';
    el.style.paddingLeft = '12px';
    el.style.color = '#475569';
  });

  // Footer
  const footer = document.createElement('div');
  footer.style.cssText = `
    margin-top: 32px;
    padding-top: 12px;
    border-top: 1px solid #e2e8f0;
    text-align: center;
    font-size: 10px;
    color: #94A3B8;
  `;
  footer.textContent = 'Generated by NoteNova AI — Smart Study Platform';

  wrapper.appendChild(header);
  wrapper.appendChild(content);
  wrapper.appendChild(footer);

  // Temporarily add to DOM for rendering (hidden)
  wrapper.style.position = 'fixed';
  wrapper.style.left = '-9999px';
  wrapper.style.top = '0';
  document.body.appendChild(wrapper);

  const opt = {
    margin: [10, 10, 10, 10],
    filename: `${filename}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: {
      scale: 2,
      useCORS: true,
      letterRendering: true,
      backgroundColor: '#ffffff',
    },
    jsPDF: {
      unit: 'mm',
      format: 'a4',
      orientation: 'portrait',
    },
    pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
  };

  try {
    await html2pdf().set(opt).from(wrapper).save();
  } finally {
    document.body.removeChild(wrapper);
  }
}
